### ISSUE TITLE
Coalignment reference distance formula

### ISSUE THREAD

**Issue by julien-cau** [fabricecordelieres/IJ-Plugin_MetroloJ#1]
Hi Fabrice,

I reviewed the changes you made to the reference distance formula. According to John's suggestion, the formula should be:
![image](https://github.com/fabricecordelieres/IJ-Plugin_MetroloJ/assets/68328447/adbab1f9-d82b-4dc5-a71f-e3ffabc677e4)
In the corrected method calcRefDist of the coalignement class, it appears you altered this. Here is the relevant code:
395 double yRef=micro.resolution[0]*micro.resolution[2]*Math.sin(phi)*Math.cos(theta);
If we follow John's suggestion, it should be:
395 double yRef=micro.resolution[0]*micro.resolution[2]*Math.sin(phi)*Math.sin(theta);

The current MetroloJ calcRefDist would result in:
![image](https://github.com/fabricecordelieres/IJ-Plugin_MetroloJ/assets/68328447/8b0d0055-36fc-4abc-bc9e-f187e8e326a3)
Is there a specific reason why you changed sin(theta) to cos(theta)? I must admit, I haven't verified the accuracy of both formulas (the original and the suggested one).
Best regards
Julien

**Comment by fabricecordelieres** [comment]
Hi,
I've re-modified the code so that it follows the exact definition given by John.
A new release has also been issued.
F.
